Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 22/08/2019
Var
// Seção de Declarações das variáveis 
area, base, altura: real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva("Informe o valor da base: ")
Leia(base)
Escreva("Informe o valor da altura: ")
Leia(altura)
area<-base*altura/2
Escreva("A area do triângulo é: ",area)
Fimalgoritmo